safe:        false
baseurl:     /
url: http://raphamorim.io/

name: Raphamorim
description: I have a passion for web development and love to create.
keywords: "raphael, amorim, developer, open, javascript, python, clojure, source"

domain: raphamorim.io
commentlinks: true
twitter-username: raphamundi
feedburnerurl: http://feeds.feedburner.com/raphamorim
google-analytics-tracking-id: UA-49746836-1
gems: [jekyll-paginate, jekyll-gist]

source:      .
destination: ./_site
paginate_path: '/page:num'

future:      true
lsi:         false
highlighter: pygments
markdown:    kramdown
permalink:   /:title/
paginate: 3

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

excerpt_separator: "<!-- more -->"
